#!/usr/bin/env bash

echo -e "\n--> Download gulp-starter\n"
curl -L https://github.com/mrhenry/gulp-starter/archive/master.zip > gulp-starter-master.zip

echo -e "\n--> Extract\n"
unzip gulp-starter-master.zip

echo -e "\n--> Copy files\n"
cp -R  gulp-starter-master/* ./
cp -R  gulp-starter-master/.[^.]* ./

echo -e "\n--> Bootstrap public folder\n"
if [ -f wp-config.php ]
then
  PROJECT_NAME=${PWD##*/}
  PROJECT_NAME=${PROJECT_NAME/wp_/''}

  if [ ! -d wp-content/themes/$PROJECT_NAME ]
  then
    mkdir -p $PROJECT_NAME
  fi

  ln -sfvn wp-content/themes/$PROJECT_NAME public

else
  mkdir -p public

fi

cp -R bootstrap-public/* public/

echo -e "\n--> Configure GIT\n"
script/config-git

echo -e "\n--> Install node modules\n"
npm install

echo -e "\n--> Install jspm\n"
jspm install

echo -e "\n--> Remove install files\n"
rm -Rf ./gulp-starter-master*
rm ./script/install

echo -e "\n--> That's it folks!\n"

cat << EOF
_  _ ____ ___  ____    ___  _   _
|\/| |__| |  \ |___    |__]  \_/
|  | |  | |__/ |___    |__]   |

_  _ ____     _  _ ____ _  _ ____ _   _
|\/| |__/     |__| |___ |\ | |__/  \_/
|  | |  \ .   |  | |___ | \| |  \   |

--> Enjoy!
EOF
